name: Environment Stages

on:
  workflow_call:
    inputs:
      action:
        description: 'Terraform Action to Execute'
        required: true
        type: string
      environment:
        description: 'Environment to deploy to (dev/prod/both)'
        required: false
        type: string
        default: 'dev'   
  
jobs:
  dev-environment:
    name: Dev Environment
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    # if: ${{ (github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request') && (inputs.environment == 'dev') }}
    uses: ./.github/workflows/terraform-steps.yml
    with:
      action: ${{ inputs.action }}
      environment: dev
      aws_region: 'ap-south-1'
      terraform_dir: '.'
      aws_role_arn: 'arn:aws:iam::859493432175:role/GithubActionsDeployments'

  prod-environment-standalone:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    name: Prod Environment (Standalone)
    needs: dev-environment
    # if: ${{ inputs.environment == 'prod' && (needs.dev-environment.result == 'skipped' || needs.dev-environment.result == 'success') }}
    uses: ./.github/workflows/terraform-steps.yml
    with:
      environment: prod
      action: ${{ inputs.action }}
      aws_region: 'ap-south-1'
      terraform_dir: '.'
      aws_role_arn: 'arn:aws:iam::859493432175:role/GithubActionsDeployments'
